export const GET_FRAMWORKS_LIST = 'GET_FRAMWORKS_LIST';
export const GET_QUESTION_LIST = 'GET_QUESTION_LIST';
export const GET_FILTERS_LIST = 'GET_FILTERS_LIST';
export const CLEAR_QUESTION_LIST = 'CLEAR_QUESTION_LIST';
export const GET_DRAFT_DATA = "GET_DRAFT_DATA";
export const CLEAR_DRAFT_DATA = "CLEAR_DRAFT_DATA";
export const GET_CREATE_RESPONSE = "GET_CREATE_RESPONSE";